name: Docker

on:
  push:
    # branches:
    #   - next
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install
      
      - name: Pre Build
        run: |
          yarn build-web
          yarn build-manage
          mkdir -p ./packages/sharelist/web/default
          mkdir -p ./packages/sharelist/manage
          wget https://raw.githubusercontent.com/linkdrive/plugins/master/list_full.json -O ./packages/sharelist/plugins.json
          cp -r ./packages/sharelist-web/dist/* ./packages/sharelist/web/default
          cp -r ./packages/sharelist-manage/dist/* ./packages/sharelist/manage
 
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./packages/sharelist/
          platforms: linux/amd64,linux/arm64
          file: ./packages/sharelist/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/sharelist:${{ env.VERSION }}
        env:
          VERSION: next
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}